# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'R0ckB0t', password: '01010101', firstName: 'Ai', lastName: 'Bainaree', email: 'progBot@gmail.com', images:'',instruments: 'Synth, Drum Machine' , influences: "New Order, Boy Harsher, Black Marble, Tears for Fears", bio: "Salutations sentients, I am here to create the most gothic music I can, or that my programming will allow.", song_url:"https://soundcloud.com/quashcheteikeheyvern/widdly-2-diddly-lisa-soundtrack-46-work-harder?si=bf96c2b7ee534a749c09b8d0580afaa3", longitude:"41.6679095 ", latitude:"69.58507")
User.create(username: 'ev3rythingevil', password: 'beansprout', firstName: 'Hathor', lastName: 'Hamilton', email: 'koshknot@gmail.com', images:'',instruments: 'Guitar, Vocals, Bass' , influences: "Blaze Foley, Laura Jane Grace, Claudio Sanchez, Ian Curtis", bio: "Hi folks! I'm looking for people to form a post punk or a doom metal band with. Let's make some music!", song_url:"https://soundcloud.com/user-632096907/naptime?si=872fcd7c70d74bddbacbea8f1882c486", longitude:"", latitude:"")
User.create(username: 'timmytimtom', password: 'dkfjgh', firstName: 'Tim', lastName: 'Tokeno', email: 'dfjg@gmail.com', images:'',instruments: ' Bass , Steel Guitar' , influences: "Blaze Foley, Hank Williams, Guy Clarke ", bio: "Hi folks! I'm looking for people to jam ol country tunes with. Let's make some music!", song_url:"https://soundcloud.com/hankwilliamsjrofficial/a-country-boy-can-survive?si=f77976f9beb84d9881c9dbe458d1f41b", longitude:"33.7490", latitude:"84.3880")
User.create(username: 'biibibio', password: 'beansprout', firstName: 'James', lastName: 'Fleetower', email: 'JTFLEE@gmail.com', images:'',instruments: 'Guitar, Drums' , influences: "Mayhem, Hellhammer, Darkthrone, Immortal", bio: "Black Metal FOREVER.", song_url:"https://soundcloud.com/kevin59500000/funeral-fog?si=a752fe2061654896ae73905ec2010d11", longitude:"59.9139", latitude:"10.7522")
User.create(username: 'aifbaiebf', password: 'beansprout', firstName: 'Griff', lastName: 'Hawke', email: 'ggFREE@gmail.com', images:'',instruments: 'Vocals' , influences: "PENPALS, The Pillows", bio: "I wanna capture and bring back the sound of 90's Japanese Alt Rock!", song_url:"https://soundcloud.com/user-850874462/kim-deal?si=64a95889dd4247e9a47c14981f799086", longitude:"35.6762", latitude:"139.6503")
User.create(username: 'toastman', password: 'beansprout', firstName: 'Lyra', lastName: 'Lane', email: 'lyraL@gmail.com', images:'',instruments: 'Guitar, Vocals, Bass, Keyboard,' , influences: "Mozart, Kate Bush, Daft Punk", bio: "Let's make some music!", song_url:"https://soundcloud.com/shakhai/penpals-tell-me-why-berserk?si=bf6cdabed74a4027975aa5cc319112f6", longitude:"40.7128", latitude:"74.0000")
